#!/bin/bash
# Force功能调试器演示脚本

echo "=== STVM Force功能调试器演示 ==="
echo ""
echo "这个演示展示如何在调试器中使用Force功能"
echo ""
echo "示例程序: debug_force_test.st"
echo "  - counter: 每次循环+1"
echo "  - temperature: 每次循环+0.5"
echo "  - alarm: 当counter>5时为TRUE"
echo ""
echo "演示步骤:"
echo "1. 编译程序为字节码"
echo "2. 启动调试器"
echo "3. 使用force命令强制变量"
echo "4. 观察程序行为变化"
echo ""

# 编译程序
echo ">>> 编译程序..."
./build/bin/stvm -c examples/debug_force_test.st -o examples/debug_force_test.stbc
if [ $? -ne 0 ]; then
    echo "编译失败！"
    exit 1
fi

echo ""
echo "编译成功！生成: examples/debug_force_test.stbc"
echo ""
echo "=== 现在可以启动调试器 ==="
echo ""
echo "运行: ./build/bin/stvm -d examples/debug_force_test.stbc"
echo ""
echo "调试器中可以使用以下Force命令:"
echo ""
echo "1. 查看帮助:"
echo "   (stdb) help"
echo ""
echo "2. 强制counter为100:"
echo "   (stdb) force counter int 100"
echo ""
echo "3. 强制temperature为999.9:"
echo "   (stdb) force temperature real 999.9 persistent"
echo ""
echo "4. 查看所有强制状态:"
echo "   (stdb) force_status"
echo ""
echo "5. 运行几步观察:"
echo "   (stdb) c"
echo "   (stdb) n"
echo "   (stdb) n"
echo ""
echo "6. 取消强制:"
echo "   (stdb) unforce counter"
echo "   (stdb) unforce all"
echo ""
echo "7. 禁用Force功能:"
echo "   (stdb) force_enable off"
echo ""
echo "8. 重新启用:"
echo "   (stdb) force_enable on"
echo ""
echo "=========================================="
echo ""
