/**
 * @file test_codegen.c
 * @brief 代码生成器测试程序
 */

#include "codegen.h"
#include "bytecode_io.h"
#include "ast.h"
#include "symtbl.h"
#include "mmgr.h"
#include <stdio.h>
#include <assert.h>
#include <string.h>

void test_simple_expression(void) {
    printf("\n--- Test: Simple Expression (2 + 3) ---\n");
    
    // 创建AST: 2 + 3
    Value val2, val3;
    val2.type = TYPE_INT;
    val2.int_val = 2;
    val3.type = TYPE_INT;
    val3.int_val = 3;
    
    ASTNode* lit2 = ast_create_literal(val2);
    ASTNode* lit3 = ast_create_literal(val3);
    ASTNode* add = ast_create_binary_op(BINOP_ADD, lit2, lit3);
    
    // 创建程序节点
    ASTNode* program = ast_create_program("test", NULL, NULL, NULL, add);
    
    // 创建字节码模块和符号表
    BytecodeModule* module = bytecode_module_create();
    SymbolTable* symtbl = symtbl_init();
    
    // 创建代码生成器
    CodeGenContext* ctx = codegen_create(module, symtbl);
    assert(ctx != NULL);
    
    // 生成代码
    ErrorCode err = codegen_generate(ctx, program);
    assert(err == OK);
    printf("✓ Generated bytecode for 2 + 3\n");
    
    // 验证指令
    assert(module->instruction_count == 4);  // PUSH 2, PUSH 3, ADD, HALT
    assert(module->instructions[0].opcode == OP_PUSH);
    assert(module->instructions[1].opcode == OP_PUSH);
    assert(module->instructions[2].opcode == OP_ADD);
    assert(module->instructions[3].opcode == OP_HALT);
    printf("✓ Instructions verified\n");
    
    // 反汇编
    printf("  Generated code:\n");
    for (int32_t i = 0; i < module->instruction_count; i++) {
        char buf[128];
        bytecode_disassemble_instruction(module->instructions[i], buf, sizeof(buf));
        printf("  %s\n", buf);
    }
    
    // 清理
    codegen_free(ctx);
    ast_free_node(program);
    bytecode_module_free(module);
    symtbl_free(symtbl);
}

void test_variable_assignment(void) {
    printf("\n--- Test: Variable Assignment (x := 42) ---\n");
    
    // 创建符号表并添加变量
    SymbolTable* symtbl = symtbl_init();
    TypeInfo* int_type = type_info_create(TYPE_INT);
    Symbol* x_sym = symtbl_define_variable(symtbl, "x", int_type, false);
    assert(x_sym != NULL);
    x_sym->is_global = true;
    x_sym->offset = 0;
    
    // 创建AST: x := 42
    Value val42;
    val42.type = TYPE_INT;
    val42.int_val = 42;
    
    ASTNode* lit42 = ast_create_literal(val42);
    ASTNode* ident_x = ast_create_identifier("x");
    ASTNode* assign = ast_create_assign(ident_x, lit42);
    
    ASTNode* program = ast_create_program("test", NULL, NULL, NULL, assign);
    
    // 生成代码
    BytecodeModule* module = bytecode_module_create();
    CodeGenContext* ctx = codegen_create(module, symtbl);
    
    ErrorCode err = codegen_generate(ctx, program);
    assert(err == OK);
    printf("✓ Generated bytecode for x := 42\n");
    
    // 验证指令: PUSH 42, STORE 0, HALT
    assert(module->instruction_count == 3);
    assert(module->instructions[0].opcode == OP_PUSH);
    assert(module->instructions[1].opcode == OP_STORE);
    assert(module->instructions[2].opcode == OP_HALT);
    printf("✓ Instructions verified\n");
    
    // 反汇编
    printf("  Generated code:\n");
    for (int32_t i = 0; i < module->instruction_count; i++) {
        char buf[128];
        bytecode_disassemble_instruction(module->instructions[i], buf, sizeof(buf));
        printf("  %s\n", buf);
    }
    
    // 清理
    codegen_free(ctx);
    ast_free_node(program);
    bytecode_module_free(module);
    type_info_free(int_type);
    symtbl_free(symtbl);
}

void test_if_statement(void) {
    printf("\n--- Test: If Statement ---\n");
    
    // 创建AST: IF x > 0 THEN y := 1 ELSE y := 0 END_IF
    SymbolTable* symtbl = symtbl_init();
    TypeInfo* int_type = type_info_create(TYPE_INT);
    
    Symbol* x_sym = symtbl_define_variable(symtbl, "x", type_info_retain(int_type), false);
    Symbol* y_sym = symtbl_define_variable(symtbl, "y", type_info_retain(int_type), false);
    x_sym->is_global = true;
    x_sym->offset = 0;
    y_sym->is_global = true;
    y_sym->offset = 1;
    
    // x > 0
    ASTNode* x = ast_create_identifier("x");
    Value val0;
    val0.type = TYPE_INT;
    val0.int_val = 0;
    ASTNode* lit0 = ast_create_literal(val0);
    ASTNode* condition = ast_create_binary_op(BINOP_GT, x, lit0);
    
    // y := 1
    Value val1;
    val1.type = TYPE_INT;
    val1.int_val = 1;
    ASTNode* lit1 = ast_create_literal(val1);
    ASTNode* y_then = ast_create_identifier("y");
    ASTNode* then_stmt = ast_create_assign(y_then, lit1);
    
    // y := 0
    ASTNode* lit0_else = ast_create_literal(val0);
    ASTNode* y_else = ast_create_identifier("y");
    ASTNode* else_stmt = ast_create_assign(y_else, lit0_else);
    
    ASTNode* if_stmt = ast_create_if(condition, then_stmt, else_stmt);
    ASTNode* program = ast_create_program("test", NULL, NULL, NULL, if_stmt);
    
    // 生成代码
    BytecodeModule* module = bytecode_module_create();
    CodeGenContext* ctx = codegen_create(module, symtbl);
    
    ErrorCode err = codegen_generate(ctx, program);
    assert(err == OK);
    printf("✓ Generated bytecode for IF statement\n");
    
    // 反汇编
    printf("  Generated code:\n");
    for (int32_t i = 0; i < module->instruction_count; i++) {
        char buf[128];
        bytecode_disassemble_instruction(module->instructions[i], buf, sizeof(buf));
        printf("  %s\n", buf);
    }
    
    // 清理
    codegen_free(ctx);
    ast_free_node(program);
    bytecode_module_free(module);
    type_info_free(int_type);
    symtbl_free(symtbl);
}

void test_while_loop(void) {
    printf("\n--- Test: While Loop ---\n");
    
    // 创建AST: WHILE x > 0 DO x := x - 1 END_WHILE
    SymbolTable* symtbl = symtbl_init();
    TypeInfo* int_type = type_info_create(TYPE_INT);
    
    Symbol* x_sym = symtbl_define_variable(symtbl, "x", int_type, false);
    x_sym->is_global = true;
    x_sym->offset = 0;
    
    // x > 0
    ASTNode* x1 = ast_create_identifier("x");
    Value val0;
    val0.type = TYPE_INT;
    val0.int_val = 0;
    ASTNode* lit0 = ast_create_literal(val0);
    ASTNode* condition = ast_create_binary_op(BINOP_GT, x1, lit0);
    
    // x := x - 1
    ASTNode* x2 = ast_create_identifier("x");
    ASTNode* x3 = ast_create_identifier("x");
    Value val1;
    val1.type = TYPE_INT;
    val1.int_val = 1;
    ASTNode* lit1 = ast_create_literal(val1);
    ASTNode* sub = ast_create_binary_op(BINOP_SUB, x3, lit1);
    ASTNode* assign = ast_create_assign(x2, sub);
    
    ASTNode* while_stmt = ast_create_while(condition, assign);
    ASTNode* program = ast_create_program("test", NULL, NULL, NULL, while_stmt);
    
    // 生成代码
    BytecodeModule* module = bytecode_module_create();
    CodeGenContext* ctx = codegen_create(module, symtbl);
    
    ErrorCode err = codegen_generate(ctx, program);
    assert(err == OK);
    printf("✓ Generated bytecode for WHILE loop\n");
    
    // 反汇编
    printf("  Generated code:\n");
    for (int32_t i = 0; i < module->instruction_count; i++) {
        char buf[128];
        bytecode_disassemble_instruction(module->instructions[i], buf, sizeof(buf));
        printf("  %s\n", buf);
    }
    
    // 清理
    codegen_free(ctx);
    ast_free_node(program);
    bytecode_module_free(module);
    symtbl_free(symtbl);
}

void test_bytecode_save_load(void) {
    printf("\n--- Test: Bytecode Save/Load ---\n");
    
    // 创建一个简单的程序
    Value val42;
    val42.type = TYPE_INT;
    val42.int_val = 42;
    ASTNode* lit = ast_create_literal(val42);
    ASTNode* program = ast_create_program("test", NULL, NULL, NULL, lit);
    
    BytecodeModule* module1 = bytecode_module_create();
    SymbolTable* symtbl = symtbl_init();
    CodeGenContext* ctx = codegen_create(module1, symtbl);
    
    ErrorCode err = codegen_generate(ctx, program);
    assert(err == OK);
    printf("✓ Generated original bytecode\n");
    
    // 保存到文件
    err = bytecode_save(module1, "test.stbc");
    assert(err == OK);
    printf("✓ Saved bytecode to test.stbc\n");
    
    // 从文件加载
    BytecodeModule* module2 = bytecode_load("test.stbc");
    assert(module2 != NULL);
    printf("✓ Loaded bytecode from test.stbc\n");
    
    // 验证内容
    assert(module2->instruction_count == module1->instruction_count);
    assert(module2->const_count == module1->const_count);
    printf("✓ Loaded module matches original\n");
    
    // 清理
    codegen_free(ctx);
    ast_free_node(program);
    bytecode_module_free(module1);
    bytecode_module_free(module2);
    symtbl_free(symtbl);
}

int main(void) {
    printf("========================================\n");
    printf("  STVM Code Generator Test Suite\n");
    printf("========================================\n");
    
    // 初始化内存管理器
    if (!mmgr_init()) {
        fprintf(stderr, "Failed to initialize memory manager\n");
        return 1;
    }
    printf("✓ Memory manager initialized\n");
    
    // 运行测试
    test_simple_expression();
    test_variable_assignment();
    test_if_statement();
    test_while_loop();
    test_bytecode_save_load();
    
    // 打印统计信息
    mmgr_print_stats();
    
    // 检查内存泄漏
    if (mmgr_check_leaks()) {
        printf("\n❌ Memory leaks detected!\n");
    } else {
        printf("\n✓ No memory leaks detected\n");
    }
    
    // 清理
    mmgr_cleanup();
    printf("✓ Memory manager cleaned up\n");
    
    printf("\n========================================\n");
    printf("  All Tests Passed! ✓\n");
    printf("========================================\n");
    
    return 0;
}
